services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-cli
    platform: linux/amd64
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis-aof
      - redis-rdb
      - beanstalkd
    environment:
      - INSTALL_EXTENSION=redis
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.10

  redis-aof:
    image: redis:latest
    platform: linux/amd64
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-aof-data:/data
    ports:
      - "6379:6379"
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.5

  redis-rdb:
    image: redis:latest
    platform: linux/amd64
    command: ["redis-server"]
    volumes:
      - redis-rdb-data:/data
    ports:
      - "6380:6379"
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.6

  beanstalkd:
    image: schickling/beanstalkd
    platform: linux/amd64
    ports:
      - "11300:11300"
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.7

volumes:
  redis-aof-data:
  redis-rdb-data:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16